services:
  frontend:
    container_name: frontend
    image: node:22-alpine
    working_dir: /usr/src/app
    volumes:
      - ./client:/usr/src/app
      - ./shared:/usr/src/shared
      - /app/node_modules
    command: sh -c "npm ci && npm run dev -- --host"
    environment:
      NODE_ENV: development
    ports:
      - 5173:5173
      - 24678:24678 # Vite Hot Module Replacement

  backend:
    container_name: backend
    image: node:22-alpine
    working_dir: /usr/src/app
    volumes:
      - ./server:/usr/src/app
      - ./shared:/usr/src/shared
      - /app/node_modules
    command: sh -c "npm ci && npm run dev"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
    ports:
      - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: postgres
    image: postgres:17.3-alpine
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./server/src/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DV: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  playwright:
    container_name: playwright
    image: mcr.microsoft.com/playwright:v1.50.0-noble
    working_dir: /tests
    volumes:
      - ./playwright:/tests
      - ./playwright/playwright-report:/tests/playwright-report
      - /tests/node_modules
    environment:
      - BASE_URL=http://frontend:5173
    depends_on:
      - frontend
      - backend
    command: sh -c "npm ci && echo 'Playwright ready!' && tail -f /dev/null"
    ports:
      - "9323:9323"
