name: Playwright Tests

on:
  push:
    branches: [ci/playwright-workflow]
    paths:
      - "playwright/**"
      - "src/**"
      - "docker-compose.yml"
  pull_request:
    branches: [dev]
  workflow_dispatch:

jobs:
  playwright:
    name: "Playwright Tests"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Start services with Docker Compose
        run: docker compose up -d frontend backend

      - name: Run Playwright in Docker
        run: |
          docker compose run --rm playwright bash -c "npm run test-docker"

      - name: Stop Docker Compose services
        if: always()
        run: docker compose down
