name: Playwright Tests

on:
  push:
    branches: [ci/playwright-workflow]
    paths:
      - "playwright/**"
      - "src/**"
      - "docker-compose.yml"
  pull_request:
    branches: [dev]
  workflow_dispatch:
jobs:
  playwright:
    name: "Playwright Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Start services with Docker Compose
        run: docker compose up -d
      - name: Wait for services to be ready
        run: sleep 15
      - name: Run Playwright Tests
        run: |
          docker exec playwright npm run test-docker
      - name: Stop Docker Compose services
        if: always()
        run: docker compose down
