name: Playwright Tests
on:
  push:
    # branches: [ci/playwright-workflow]
  pull_request:
    branches: [dev]
  workflow_dispatch:
jobs:
  playwright:
    name: "Playwright Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Start frontend backend and postgres docker containers
        run: docker compose up -d frontend backend postgres
      - name: Wait for services to be ready
        run: sleep 30
      - name: Install dependencies
        run: cd playwright && npm ci
      - name: Install Playwright Browsers
        run: cd playwright && npx playwright install --with-deps
      - name: Run Playwright tests
        run: cd playwright && npm run test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: ./playwright/playwright-report/
          retention-days: 7
      - name: Show docker logs
        run: docker compose logs
      - name: Stop Docker Compose services
        if: always()
        run: docker compose down
