name: Server api and unit tests
on:
  push:
  workflow_dispatch:
jobs:
  server-tests:
    name: "Server api and unit tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start backend and postgres docker containers
        run: docker compose up -d backend postgres
      - name: Wait for services to be ready
        run: sleep 30
      - name: Unit tests
        run: docker exec backend npm run test-unit
      - name: Api tests
        run: docker exec backend npm run test-api
      - name: Stop docker containers
        if: always()
        run: docker compose down
