name: Run Tests
on:
  push:
    branches: [ "main", "dev", "test-dev-actions-server" ]
  pull_request:
    branches: [ "main", "dev", "test-dev-actions-server" ]
jobs:
  server-tests:
    name: Server Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    strategy:
      matrix:
        node-version: [22.x]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        cache-dependency-path: '**/server/package-lock.json'
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: Run ESLint
      uses: sibiraj-s/action-eslint@v3
      with:
        eslint-args: '--max-warnings=0'
        extensions: '.js,.jsx,.ts,.tsx'
        working-directory: './server'
    - run: npm run build --if-present
    - run: npm install cross-env
    - run: CI=true npm run test-unit
    - run: CI=true npm run test-api

  client-lint:
    name: Client Lint Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    strategy:
      matrix:
        node-version: [22.x]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        cache-dependency-path: '**/client/package-lock.json'
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: Run ESLint
      uses: sibiraj-s/action-eslint@v3
      with:
        eslint-args: '--max-warnings=0'
        extensions: '.js,.jsx,.ts,.tsx'
        working-directory: './client'
